# Generated by Django 6.0.3 on 2026-03-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='✓', help_text='Emoji o carácter. Ej: 🌐 ❄ 🅿 🍳', max_length=10)),
                ('nombre', models.CharField(help_text='Ej: WiFi Gratis, Alberca', max_length=80)),
                ('descripcion', models.CharField(blank=True, default='Disponible para todos los huéspedes', max_length=160)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades del Hotel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Hotel, Habitaciones, Restaurante', max_length=60)),
                ('slug', models.SlugField(help_text='Ej: hotel, habitaciones, restaurante', unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Galería',
                'verbose_name_plural': 'Categorías de Galería',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Av. Reforma 123, Mexicali, BC', max_length=255)),
                ('telefono', models.CharField(default='+52 686 000 0000', max_length=30)),
                ('email', models.EmailField(default='info@hotelregis.mx', max_length=254)),
                ('whatsapp_number', models.CharField(default='526860000000', help_text='Solo números, ej: 526861234567', max_length=20)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/hotelregismexicali')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ej: 50+, 30, ★4.8, 24/7', max_length=20)),
                ('etiqueta', models.CharField(help_text='Ej: Habitaciones, Años de Historia', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: Suite Ejecutiva, Doble Estándar', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción breve de la habitación')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por noche en MXN', max_digits=8)),
                ('miniatura', models.ImageField(help_text='Foto principal (600×400px)', upload_to='habitaciones/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Recomendado: 1920×1080px', upload_to='hero/')),
                ('alt', models.CharField(blank=True, default='Hotel Regis Mexicali', max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen Hero',
                'verbose_name_plural': 'Imágenes Hero (Carrusel Principal)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del restaurante (800×600px)', upload_to='restaurante/')),
                ('alt', models.CharField(blank=True, default='Restaurante Villa Don Nacho', max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto Restaurante',
                'verbose_name_plural': 'Fotos Restaurante (Galería)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ciudad', models.CharField(blank=True, default='México', max_length=80)),
                ('texto', models.TextField(help_text='Comentario del huésped')),
                ('estrellas', models.PositiveSmallIntegerField(default=5, help_text='Del 1 al 5')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AmenidadHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: WiFi, A/C, TV, Desayuno', max_length=60)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidades', to='hotel.habitacion')),
            ],
            options={
                'verbose_name': 'Amenidad de Habitación',
                'verbose_name_plural': 'Amenidades de Habitación',
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto para la galería general', upload_to='galeria/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='hotel.categoriagaleria')),
            ],
            options={
                'verbose_name': 'Imagen Galería',
                'verbose_name_plural': 'Imágenes Galería General',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Fotos adicionales del cuarto', upload_to='habitaciones/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hotel.habitacion')),
            ],
            options={
                'verbose_name': 'Foto de Habitación',
                'verbose_name_plural': 'Fotos de Habitación',
                'ordering': ['orden'],
            },
        ),
    ]
